services:
    app:
        build:
            context: .
            dockerfile: docker/app.Dockerfile
        image: mylaravel/php81-app
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - '/home/unsl/laravel/storage/storagetask:/var/www/html'
            - './docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro'
        env_file:
            - .env
        depends_on:
            - mysql
    web:
        image: 'nginx:1.26-alpine'
        container_name: web
        restart: unless-stopped
        ports:
            - '8080:80'
        volumes:
            - '/home/unsl/laravel/storage/storagetask:/var/www/html:ro'
            - './docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro'
        depends_on:
            - app
    mysql:
        image: 'mysql:8.0'
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
            MYSQL_USER: '${DB_USERNAME:-laravel}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'mysqldata:/var/lib/mysql'
        ports:
            - '3307:3306'
volumes:
    mysqldata: null
    sail-pgsql:
        driver: local
